#!/usr/bin/env bash
# Transfer file to server using ssh
if [ "$#" -lt 3 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1;
fi
# FILEPATH=$1
IP=$2
UNAME=$3
SSH_PATH=$4

# ssh "${UNAME}@${IP}" -i "$SSH_PATH" 'ls ~/'

# ssh "${UNAME}@${IP}" -i "$SSH_PATH" 'scp -o StrictHostKeyChecking=no "$1" "${UNAME}@${IP}:~/"'
scp -i "$SSH_PATH" -o StrictHostKeyChecking=no "$1" "${UNAME}@${IP}:~/"
