#!/usr/bin/env bash
# Install nginx on server
sudo apt-get update -y
sudo apt-get -y install nginx
# sudo service nginx start
sudo mkdir -p /var/www/html
echo "Holberton School for the win!" > /var/www/html/index.html
sudo service nginx start
