#!/usr/bin/env bash
# Configure Nginx server so that /redirect_me is redirecting to another page.
sudo apt-get update -y
sudo apt-get -y install nginx
sudo mkdir -p /var/www/html
echo "Holberton School for the win!" > /var/www/html/index.html
sudo service nginx start
