#!/usr/bin/env bash
# Install 2nd nginx on server 983-web-02
sudo apt-get update -y
sudo apt-get -y install nginx
sudo mkdir -p /var/www/html
echo "Holberton School for the win!" > /var/www/html/index.html
sudo service nginx restart
