#!/usr/bin/env bash
# Install 2nd nginx on server 983-web-02
sudo apt-get update -y
sudo apt-get -y install nginx
sudo mkdir -p /var/www/html
echo "Holberton School" >> /var/www/html/index.html
sudo sed -i "25i\ \tadd_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf
sudo service nginx start
