#!/usr/bin/env bash
# Install 2nd nginx on server 983-web-02
sudo apt-get update -y
sudo apt-get -y install nginx
sudo mkdir -p /var/www/html
echo "add_header X-Served-By  983-web-01" >> /etc/nginx/nginx.conf
echo "add_header X-Served-By  983-web-02" >> /etc/nginx/nginx.conf
sudo service nginx start
