#!/usr/bin/env bash
# generates a MySQL dump and creates a compressed archive out of it.
now=$(date +"%d-%m-%Y")
mysqldump -uroot -p"$1" --all-databases > backup.sql
tar -zcf "$now".tar.gz ./backup.sql
