#!/usr/bin/env bash
# Manage manage_my_process

/etc/init.d/start OPTION
$(manage_my_process)
ps $$ | sudo tee /var/run/holbertonscript.pid
trap "echo 'I hate the kill command'" SIGTERM
trap "echo 'Y U no love me?!'" SIGINT
trap "rm /var/run/holbertonscript.pid; exit" SIGQUIT SIGTERM

# /etc/init.d/stop OPTION

# /etc/init.d/restart OPTION
