#!/usr/bin/env bash
# Endless loop, trap SIGTERM, SIGKILL, SIGINT, SIGTERM, SIGQUIT
trap "echo 'I hate the kill command'" SIGTERM
trap "echo 'Y U no love me?!'" SIGINT
trap "rm /var/run/holbertonscript.pid; exit" SIGQUIT SIGTERM
while :
do
	echo "To infinity and beyond"
	sleep 2
done
