#!/usr/bin/env bash
# Change your home IP
if  [ "$(grep -Fx '127.0.0.1 localhost' /etc/hosts)" ]
then
    sed -i "s/127.0.0.1 localhost/127.0.0.2 localhost/" /etc/hosts
else
    echo "127.0.0.2 localhost" >> /etc/hosts
fi
echo "8.8.8.8 facebook.com" >> /etc/hosts
