#!/usr/bin/env bash
# Run Nginx as Nginx
pkill apache2
sudo chown nginx:nginx /etc/nginx/nginx.conf
sudo chmod 644 /etc/nginx/nginx.conf
sudo sed -i 's/#user www-data;/user nginx;/g' /etc/nginx/nginx.conf
sudo sed -i 's/80 default_server/8080 default_server/' /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
